version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  project: olcEngineSpriteEditor.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: Sprite Editor\bin\Debug\
  name: debug
- path: Sprite Editor\bin\Release\
  name: release
